[project]
name = "geocruncher-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "celery>=5.5.3",
    "flask>=3.1.1",
    "redis>=6.4.0",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
